# Netlify configuration file

[build]
  command = "npm run build"
  publish = "out"  # Use "out" if you're using `next export`, otherwise let the plugin handle it.

[functions]
  timeout = 26

# Enable the official Next.js plugin for full SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"
