[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

  # If you want to increase timeout, do this per-function (or via Netlify UI)
  # You can set specific function configs like this:
  [functions."api/auth/login"]
    timeout = 26
